name: five_on_4_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

dependencies:
  args: ^2.4.0
  collection: ^1.18.0
  crypt: ^4.3.1
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.13.0
  dio: ^5.4.2
  drift: ^2.16.0
  drift_postgres: ^1.2.0
  envied: ^0.5.3
  equatable: ^2.0.5
  mocktail: ^1.0.3
  postgres: ^3.1.2
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  stormberry: ^0.14.0

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.16.0
  envied_generator: ^0.5.3
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
